### ISSUE TITLE
‘CEC_CLIENT_VERSION_CURRENT’ is not a member of ‘CEC’

### ISSUE THREAD

**Issue by jbadger** [rtyle/r2upnpav#1]
Unable to make the r2upnpav project because of the following error on my Raspberry Pi 3 model B.

``` sh
root@raspberrypi:/home/pi/r2upnpav# make
g++ -pthread -I/usr/local/include -I/usr/local/include/libcec -I/usr/local/include -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include/gupnp-av-1.0 -I/usr/include/gupnp-1.0 -I/usr/include/gssdp-1.0  -I /usr/include/lirc -g -std=c++0x -o r2upnpav r2upnpav.cc -L/usr/local/lib -lgupnp-1.0 -lgupnp-av-1.0 -lgssdp-1.0 -lgobject-2.0 -lglib-2.0 -lcec -lp8-platform  -lboost_program_options -lboost_regex -lboost_system -llirc_client
r2upnpav.cc: In constructor ‘CecInput::Adapter::Configuration::Configuration(void*, const char*)’:
r2upnpav.cc:752:19: error: ‘CEC_CLIENT_VERSION_CURRENT’ is not a member of ‘CEC’
   clientVersion = CEC::CEC_CLIENT_VERSION_CURRENT;
                   ^
makefile:23: recipe for target 'r2upnpav' failed
make: *** [r2upnpav] Error 1
```

Looks like there was a change in how version numbers are represented, but i'm not familiar with C.
https://github.com/Pulse-Eight/libcec/blob/master/include/version.h.in

**Comment by rtyle** [comment]
Maybe try ...
CEC::CEC_CLIENT_VERSION_2_2_0
... instead?.
Normally, I would think, that would be bad practice (lying) as you should use what is (currently) installed (tell the truth).
CEC::CEC_CLIENT_VERSION_CURRENT
shares the same value: 0x2200
Yes, from your reference, it looks like versions 2.3.0 and later are encoded differently.

What does your cectypes.h have for versions?
Mine has

typedef enum cec_client_version
{
  CEC_CLIENT_VERSION_PRE_1_5 = 0,
  CEC_CLIENT_VERSION_1_5_0   = 0x1500,
  CEC_CLIENT_VERSION_1_5_1   = 0x1501,
  CEC_CLIENT_VERSION_1_5_2   = 0x1502,
  CEC_CLIENT_VERSION_1_5_3   = 0x1503,
  CEC_CLIENT_VERSION_1_6_0   = 0x1600,
  CEC_CLIENT_VERSION_1_6_1   = 0x1601,
  CEC_CLIENT_VERSION_1_6_2   = 0x1602,
  CEC_CLIENT_VERSION_1_6_3   = 0x1603,
  CEC_CLIENT_VERSION_1_7_0   = 0x1700,
  CEC_CLIENT_VERSION_1_7_1   = 0x1701,
  CEC_CLIENT_VERSION_1_7_2   = 0x1702,
  CEC_CLIENT_VERSION_1_8_0   = 0x1800,
  CEC_CLIENT_VERSION_1_8_1   = 0x1801,
  CEC_CLIENT_VERSION_1_8_2   = 0x1802,
  CEC_CLIENT_VERSION_1_9_0   = 0x1900,
  CEC_CLIENT_VERSION_1_99_0  = 0x1990,
  CEC_CLIENT_VERSION_2_0_0   = 0x2000,
  CEC_CLIENT_VERSION_2_0_1   = 0x2001,
  CEC_CLIENT_VERSION_2_0_2   = 0x2002,
  CEC_CLIENT_VERSION_2_0_3   = 0x2003,
  CEC_CLIENT_VERSION_2_0_4   = 0x2004,
  CEC_CLIENT_VERSION_2_0_5   = 0x2005,
  CEC_CLIENT_VERSION_2_1_0   = 0x2100,
  CEC_CLIENT_VERSION_2_1_1   = 0x2101,
  CEC_CLIENT_VERSION_2_1_2   = 0x2102,
  CEC_CLIENT_VERSION_2_1_3   = 0x2103,
  CEC_CLIENT_VERSION_2_1_4   = 0x2104,
  CEC_CLIENT_VERSION_2_2_0   = 0x2200,
  CEC_CLIENT_VERSION_CURRENT = 0x2200
} cec_client_version

**Comment by jbadger** [comment]
Same issue using `CEC_CLIENT_VERSION_2_2_0`.  I tried hard coding it to 0x2200 and get the following

```
root@raspberrypi:/home/pi/r2upnpav# ./r2upnpav -v
    CEC log D   47  Broadcast (F): osd name set to 'Broadcast'
    CEC log D   47  InitHostCEC - vchiq_initialise succeeded
    CEC log D   47  InitHostCEC - vchi_initialise succeeded
    CEC log D   47  InitHostCEC - vchi_connect succeeded
    CEC log D   48  Open - vc_cec initialised
    CEC log D   48  logical address changed to Free use (e)
    CEC log N   48  connection opened
    CEC log E   48  failed to register a new CEC client: client version 34.0.0 is no longer supported
    CEC log E   48  failed to register a CEC client
    CEC log D   48  processor thread started
    CEC log D   49  unregistering all CEC clients
CEC::ICECAdapter::Open failed
```

```
root@raspberrypi:/home/pi/r2upnpav# cec-client
No device type given. Using 'recording device'
CEC Parser created - libCEC version 3.1.0
```

Looks like 3.1.0 does not include cec_client_version.  See [gist](https://gist.github.com/jbadger/a8a8b5e1e58917aa4605).  I do see the following

```
typedef enum cec_version
{
  CEC_VERSION_UNKNOWN = 0x00,
  CEC_VERSION_1_2     = 0x01,
  CEC_VERSION_1_2A    = 0x02,
  CEC_VERSION_1_3     = 0x03,
  CEC_VERSION_1_3A    = 0x04,
  CEC_VERSION_1_4     = 0x05
} cec_version;
```

Hard coding the clientVersion to 0x3100 gives me the following

```
root@raspberrypi:/home/pi/r2upnpav# ./r2upnpav -v
    CEC log D   29  Broadcast (F): osd name set to 'Broadcast'
    CEC log D   29  InitHostCEC - vchiq_initialise succeeded
    CEC log D   29  InitHostCEC - vchi_initialise succeeded
    CEC log D   29  InitHostCEC - vchi_connect succeeded
    CEC log D   30  Open - vc_cec initialised
    CEC log D   30  logical address changed to Free use (e)
    CEC log N   30  connection opened
    CEC log E   30  failed to register a new CEC client: client version 0.49.0 is no longer supported
    CEC log E   30  failed to register a CEC client
    CEC log D   31  processor thread started
    CEC log D   31  unregistering all CEC clients
CEC::ICECAdapter::Open failed
```

**Comment by rtyle** [comment]
I guess that's what we get when we lie to your "current" CEC library.

Their example client ...
https://github.com/Pulse-Eight/libcec/blob/master/src/cec-client/cec-client.cpp
... codes it like this ...
g_config.clientVersion = LIBCEC_VERSION_CURRENT;

Can you try that?

**Comment by rtyle** [comment]
here is the diff of the commit that made the change, I think ...
https://github.com/Pulse-Eight/libcec/commit/a8259e9b1a0d79c5f8dcb381abd854dd0076e14c

**Comment by jbadger** [comment]
Project builds and runs when I use LIBCEC_VERSION_CURRENT.

**Comment by rtyle** [comment]
> builds and runs ...

Good.
When I get a chance I'll see what I can do to make the code compile with old (my) and new (yours) versions.
I hope it works for you!

**Comment by rtyle** [comment]
LIBCEC_VERSION_CURRENT works for the old stuff too.
I have committed the change.
Thanks.

**Comment by jbadger** [comment]
Pulled the latest commit and compiled just fine.  Thanks!
